version: 2
jobs:
  build:
    working_directory: ~/graph-workload
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn          
      - run:
          name: test
          command: yarn run test
      - run:
          name: Build Docker Container
          command: docker build -t mdavidallen/graph-workload:latest -f Dockerfile .
      - run:
          name: Deploy to Docker Hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              echo "Pushing docker image"
              docker push mdavidallen/graph-workload:latest
            else
              echo "Not deploying; not master branch."
            fi
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml